name: Self Test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: self-test
        uses: ./
        with:
          version: major
          dry-run: true
      - name: Show outputs
        run: |
          cat <<EOT
            ${{ toJson(steps.self-test.outputs) }}
          EOT
