name: Self test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: composite-action
        uses: ./
        with:
          version: major
          dry-run: true
      - run: |
          echo ${{ steps.self-test.outputs.tags }}
